### PR TITLE
allow steps to be controlled via keyboard

### PR DESCRIPTION
**Pull request by diego-vieira**
I have used `grunt release` but it bumped version to `0.4.1`.
Perhaps it should be bumped to `0.5.0`.

I didn't write any test, because this would require e2e runner like protractor.

### CODE REVIEW

**Comment by benmarch** [comment]
Thanks, @diego-vieira! I'll look it over and work on getting it into the next release. Can I actually ask you to revert the version bump? I will merge in the changes with some other changes I have made and do the version bump once that is all working.

Thanks!
Ben

**Comment by diego-vieira** [comment]
@benmarch done as requested.

**Comment by benmarch** [comment]
Hey @diego-vieira, I merged your changes but made a slight modification (moved the code to their own functions for readability). I am going to create a pre-release for 0.5.0 shortly, please try it out and let me know if it works for you. Thank you for taking the time to set this up, it's a fantastic feature!

**Comment by benmarch** [comment]
Also went with "useHotkeys" instead of "hotkeys" for the option name. Just a personal style :smile:

**Comment by diego-vieira** [comment]
@benmarch awesome - no problem with personal style - I tried to fit in the best location, but knew you could improve it. Will give it a go and let you know

**Pull request merged**
