### PR TITLE
Fix for #68 - Multiple tours with multiple steps

### PR DESCRIPTION
**Pull request by skalamichal**
Added support for detached tour steps for elements with ngIf, ngInclude, ...

### CODE REVIEW

**Comment by benmarch** [comment]
Sorry for the delay, I had family visiting for a long weekend. This looks good, merging...

**Comment by skalamichal** [comment]
Great, when do you expect will it be available in the release?

**Comment by benmarch** [comment]
All set, released version 0.6.3.

**Comment by skalamichal** [comment]
Thank you.

**Comment by skalamichal** [comment]
Hi Ben,

I noticed that the dist folder has still the issue, so when you install the module from bower repo, it has still the bug. I haven't added to the git commit the dist folder. Would you do it?

Michal

**Comment by benmarch** [comment]
Hey Michal,

Thank you for pointing that out! I'll re-release 0.6.4 now. Sorry about that!

Ben

**Comment by benmarch** [comment]
Ok 0.6.4 is released. So sorry about that!

**Comment by skalamichal** [comment]
No problem, thank you.

Michal

**Pull request merged**
