### PR TITLE
changes in the backdrop, clone and preventScrolling() call and readme…

### PR DESCRIPTION
**Pull request by cesarcosta99**
The backdrops now are just a transparent background to prevent any interactions with the background elements;
The clone is a transparent div that has a shadow to highlight the _backdropped_ element;
`preventScrolling()` was moved to the top of the function to avoid calculation errors caused by `no-scrolling` class;
Added `startedAt(step)` in the docs.

### CODE REVIEW

**Comment by benmarch** [comment]
Wow, thanks @cesarcosta99! I will play around with this and make sure that it passes my local testing environment. Can I ask that you remove the startAt() documentation as I have added that along with a couple other things locally already. I am planning to release 0.5.0 next week with fixes for all (or most) of the open issues, and I will include this if everything looks good.

Thanks again!
Ben

**Comment by cesarcosta99** [comment]
You're welcome! It was my first PR, do I have to make a new PR to remove the documentation change? How to proceed?

**Comment by benmarch** [comment]
All you have to do is push to the same branch and it will update the PR. Don't use --amend though, that will require a force push.

**Comment by cesarcosta99** [comment]
I added a transition effect with the backdrops in my project, do you want to take a look? I could commit it later.

**Comment by benmarch** [comment]
I think I'll hold off on additional styles for now. I was actually thinking of removing all styles from the backdrop and just adding a class so that users could implement whatever styles they want (maybe include a default). What do you think about that?

**Comment by cesarcosta99** [comment]
I think it's a great idea, it means more possibilities to the plugin. And what I suggested  is a bad idea actually, I was thinking in others but I need to think in the whole plugin just like you did.

**Comment by benmarch** [comment]
Hey @cesarcosta99, I have decided not to merge these changes for a few reasons. It looks like this solution basically creates a window that visually blocks out everything but the target element, but also prevents interaction with the target. There have been a couple issues now about interacting with the target content when the backdrop is present, and both the current implementation and this implementation prevent interaction in one way or another.

With all of this in mind, I have completely reengineered the backdrop. It is no longer a single element with a cloned target, it is a construct of 4 elements that are positioned around the target without covering it. When styled (yes, I removed the default styles and added a "tour-backdrop" class) it will appear exactly as the original backdrop with cloned target looked, but it will allow the user to interact with the original target element. 

I also used your suggestion of preventing the scrolling _before_ positioning the backdrop, which should solve the issue that you were facing. Thank you for taking the time to make these changes, and I'm sorry I ended up not merging them (your code is sound, I just have to go with a different implementation). I appreciate all of the feedback you have provided so far, it has greatly improved this plugin. Please keep it coming!

**Comment by cesarcosta99** [comment]
No problem, @benmarch, I liked your solution and it's better if someone wants the interaction with the element, but I suggest you to provide an option to prevent the interaction by adding the 5th element covering the original one because the same way people want the interaction others may not want. Don't worry about not merging my changes, thanks for the support and depending on me I'll keep feed backing to improve it. :smile:

**Comment by cesarcosta99** [comment]
Other suggestion I was thinking is to add a global option to prevent scrolling like `ui-tour-prevent-scrolling` for who wants to prevent scrolling in all tour instead of adding on each step. What do you think?

**Pull request closed without merging**
